# Generated by Django 3.0.5 on 2021-05-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210510_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
