# Generated by Django 3.0.5 on 2021-05-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210510_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userid',
            new_name='asas',
        ),
    ]
