# Generated by Django 3.0.5 on 2021-05-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210510_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asas',
        ),
    ]
