# Generated by Django 3.0.5 on 2021-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_profile_asas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
