# Generated by Django 3.0.5 on 2021-05-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210510_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof',
            field=models.ImageField(default=None, upload_to='profs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
