# Generated by Django 3.0 on 2021-05-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210510_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prof',
        ),
    ]
