# Generated by Django 3.0.5 on 2021-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210510_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof',
            field=models.ImageField(default=None, upload_to='prof-img'),
        ),
    ]
