# Generated by Django 3.0.5 on 2021-05-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_profile_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prof',
        ),
    ]
