# Generated by Django 3.0.5 on 2021-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_profile_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prof',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
