# Generated by Django 3.0.5 on 2021-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20210510_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('pear', 'Pear'), ('foss', 'FOSS'), ('arch', 'Arch')], max_length=200),
        ),
    ]
