# Generated by Django 3.0.5 on 2021-05-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210510_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('pear', 'Pear'), ('foss', 'FOSS'), ('arch', 'Arch'), ('anime1', 'Anime 1'), ('anime2', 'Anime 2')], max_length=200),
        ),
    ]
