# Generated by Django 3.0 on 2021-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='body_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
