# Generated by Django 3.0.5 on 2021-05-05 18:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=tinymce.models.HTMLField(),
        ),
    ]
