# Generated by Django 3.0.5 on 2021-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210505_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
    ]
