# Generated by Django 3.0.5 on 2021-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Gaming', 'Game'), ('devel', 'Development'), ('art', 'Arts')], default=True, max_length=255),
        ),
    ]
