# Generated by Django 3.0.5 on 2021-05-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210511_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
