# Generated by Django 3.0.5 on 2021-05-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210511_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
