# Generated by Django 3.0.5 on 2021-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210512_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('ermia', 'Ermia'), ('sareha', 'Eareha'), ('Anonymous', 'Ghost')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Gaming', 'Game'), ('devel', 'Development'), ('art', 'Arts')], default=None, max_length=255),
        ),
    ]
