# Generated by Django 3.0.5 on 2021-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210512_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('ermia', 'Ermia'), ('sareha', 'Sareha'), ('Anonymous', 'Ghost')], max_length=100),
        ),
    ]
